### ISSUE TITLE
feat: Add support for indexes in interfaces.

### ISSUE THREAD

**Issue by diosney** [gristlabs/ts-interface-builder#10]
Currently if an index signature is added to an interface, the generated file has bad syntax and does not compile.

**Comment by diosney** [comment]
Hi! I'm using the flag to ignore the index, but still the generated file has a bad syntax.

I'm using a mix with both an index and declared fields, something like:

```
interface Test {
   [index: string]: string;
   someFieldHere: IFieldMap // (another interface)
}
```
but it could be awesome that indices support gets added :) it is very cumbersome to live without them hahaha.

Thanks!

**Comment by dsagal** [comment]
This is still working for me. Can you include a complete reproducible example of the problem, with input output, the version of ts-interface-builder you are using, and the command line you are running?
