### ISSUE TITLE
Support intersection types

### ISSUE THREAD

**Issue by josejulio** [gristlabs/ts-interface-builder#15]
When trying to process and intersection type, it yields:

```
Node IntersectionType not supported by ts-interface-builder: {
  sessionInfo: SessionInfo;
} & AuthConfig
```

**Comment by minism** [comment]
Any comments from the authors on this?  Is this reasonable to do, and if so how difficult is it?  I would be willing to help.  Or are there known hard limitations?

**Comment by minism** [comment]
Ended up taking a stab at this in #20

**Comment by Sheeler** [comment]
Are there any plans to release this on NPM? I saw a matching change for the ts-interface-checker get released.

**Comment by minism** [comment]
@dsagal For the above question

**Comment by dsagal** [comment]
Just published. Thanks @minism!
