### ISSUE TITLE
Support for `[key: string]:  { ... }` style objects

### ISSUE THREAD

**Issue by PaulGrimshaw** [gristlabs/ts-interface-builder#21]
We often use this to type our config, e.g.

```
export interface ServerConfig {
    redis: {
        host: string
        port?: number
    }
    timezone?: string
    jobQueuePrefix: string
    loggers?: { [key: string]: { type: string, config: any } }

    queues: { [key: string]: JobQueue}
    jobs: { [key: string]: Job}
    schedules: { [key: string]: Schedule }
}
```

Would be great if the interface checker supported this.

**Comment by dsagal** [comment]
True. This is index signatures, and not yet supported by either `ts-interface-builder` or `ts-interface-checker`. There is a flag `--ignore-index-signature` that at least allows such interfaces to compile.

Proper support would take a little work in both `ts-interface-builder` and `ts-interface-checker`. It shouldn't be too difficult, I just don't have the time for it. But will happily review pull requests!

**Comment by PaulGrimshaw** [comment]
Id be happy to have a crack at it - would you be able to give me a couple getting started pointers?  Just where to introduce the logic and where to setup the tests (will do interface-builder first).

**Comment by dsagal** [comment]
Great! This recent pull request is a simple but sufficient example of adding support for a TypeScript construct: https://github.com/gristlabs/ts-interface-builder/pull/20
