### ISSUE TITLE
Inheritance support

### ISSUE THREAD

**Issue by robdubparker** [gristlabs/ts-interface-builder#45]
Any chance we could add support for inheritance?  

**Example:**
`export interface ShapeRotator extends Wordcel {}`

In the above example, ShapeRotator wouldn't include the types from Wordcel interface.  Is it possible to add this functionality?

**Comment by dsagal** [comment]
Hmm, I think this does work, and is tested here: https://github.com/gristlabs/ts-interface-builder/blob/8ff1a0c9f4b59d5b5038f366fb485f344ae70813/test/fixtures/sample.ts#L43

**Comment by robdubparker** [comment]
Thanks for the quick reply.  I'll take another look on my end, as I may have overlooked something.

**Comment by robdubparker** [comment]
Ok, it looks like my issue is more specific to the enum type.  

Example:

```
// imports an enum declaration from a shared library.  This does not include
// the types during the ts-interface-builder build.
import { ShapeStatus } from "pathTo/someCommonLib";

// Does not help.
export { ShapeStatus }
```
So, in this case, the enum needs to be declared again (adds complexity), since we cannot extend enums.

Understandably, this may be outside the scope of what the module is meant to do.
